### ISSUE TITLE
Easy way to show correct Total Received amount for each address

### ISSUE THREAD

**Issue by naghajani** [bitpay/bitcore-node#464] opened 2016-06-30 01:52 UTC
Hello and Thank you for all the efforts,

IMO the output of "Total Received" is not correct and not useful.

Example (check the difference in Total Received):
[https://insight.bitpay.com/address/17WqA7z67HvhNoSaZ4X5YfuhwW2hjSRViQ](https://insight.bitpay.com/address/17WqA7z67HvhNoSaZ4X5YfuhwW2hjSRViQ)
[https://blockchain.info/address/17WqA7z67HvhNoSaZ4X5YfuhwW2hjSRViQ](https://blockchain.info/address/17WqA7z67HvhNoSaZ4X5YfuhwW2hjSRViQ)

1. Any plans or methods to change this?
2. If not, how can we correctly calculate "Total Received" amount at the moment?

Thanks again and apologies if this is not where we should ask such questions, I am not familiar with Github atm.

**Comment by gabegattis** [comment] 2016-06-30 20:18
Hey, @naghajani, thanks for the feedback. This is something that we have thought about before, but we don't have plans to make any changes in the immediate future.

I don't know exactly how blockchain.info calculates their "Total Received" number, but I imagine that they are making assumptions about change addresses that we are not making.

Our calculation is a naive implementation that simply sums up every output sent to an address.

There are several different ways you could go about this, each getting different results. All of them are technically correct, but have slightly different meanings.

One way is to ignore specific inputs and outputs and just look at whether a transaction increased the balance of a given address or decreased it. The difference would be the amount sent/received for that tx. This heuristic works well for the most common case of a single address that just sends and receives normal transactions.

When you have more sophisticated transactions with lots of inputs and outputs, things like coinjoin, etc. the previous heuristic may not be best. Another way is to look at the individual inputs and outputs to see how much should be considered change. It's still not perfect though.

**Comment by naghajani** [comment] 2016-07-01 03:27
Thank you for your kind reply @gabegattis ,

But I think there is no guessing needed at all,

I searched in Blockchain to find a very simple example:

Please check this example that I found:
[https://blockchain.info/address/1CZUCh2XaM9q7WBiV6GL1yMLe9yDpRvfuP](https://blockchain.info/address/1CZUCh2XaM9q7WBiV6GL1yMLe9yDpRvfuP)
[https://insight.bitpay.com/address/1CZUCh2XaM9q7WBiV6GL1yMLe9yDpRvfuP](https://insight.bitpay.com/address/1CZUCh2XaM9q7WBiV6GL1yMLe9yDpRvfuP)

This account has only 2 transactions, so we can see what they are doing, there is no guessing involved.

If there is a transaction like this:
Z -----> X
   -----> Y
   -----> Z

The amount from Z to Z doesn't count as Total Received ([as you can see here](http://i.imgur.com/1gmflNE.png)).

even simpler: any amount moved from Z to Z:
Z -----> Z
Should be ignored in Total Received (if they are not ignored then it's like adding these amounts to Balance as well)

----------

But then again, I haven't participated in this project and can't ask for you guys to put time in it, I'm thankful for your efforts as it is now.

**Comment by braydonf** [comment] 2016-07-01 12:26
FYI the implementation is at `getaddressbalance` https://github.com/bitpay/bitcoin/blob/0.12.1-bitcore/src/rpcmisc.cpp#L722-L730

Also related is the `getaddressdeltas` method that returns all balance changes to an address from an input or output: https://github.com/bitpay/bitcoin/blob/0.12.1-bitcore/src/rpcmisc.cpp#L597

**Comment by braydonf** [comment] 2016-07-01 13:56
Duplicate of: https://github.com/bitpay/bitcore-node/issues/373

**Closed by braydonf** 2016-07-01 13:56 UTC
Labels: duplicate, feature request, support request
