### ISSUE TITLE
error code ELIFECYCLE

### ISSUE THREAD

**Issue by Alesfatalis** [bitpay/bitcore-node#200] opened 2015-09-05 16:21 UTC
This is my second attempt in getting bitcore-node to run. On my first attempt the bitcoin client synced full but bitcore-node failed to process a block with a error that the Block Data is compressed or so.

On my second attempt with the latest beta I get this error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/dev1/.nvm/versions/node/v0.12.7/bin/node',
1 verbose cli   '/home/dev1/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart bitcore-node@0.2.0-beta.5
6 info start bitcore-node@0.2.0-beta.5
7 verbose unsafe-perm in lifecycle true
8 info bitcore-node@0.2.0-beta.5 Failed to exec start script
9 verbose stack Error: bitcore-node@0.2.0-beta.5 start: `node bin/start.js`
9 verbose stack Exit status 139
9 verbose stack     at EventEmitter.<anonymous> (/home/dev1/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/home/dev1/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid bitcore-node@0.2.0-beta.5
11 verbose cwd /home/dev1/bitcore-node
12 error Linux 3.19.0-15-generic
13 error argv "/home/dev1/.nvm/versions/node/v0.12.7/bin/node" "/home/dev1/.nvm/versions/node/v0.12.7/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error bitcore-node@0.2.0-beta.5 start: `node bin/start.js`
17 error Exit status 139
18 error Failed at the bitcore-node@0.2.0-beta.5 start script 'node bin/start.js'.
18 error This is most likely a problem with the bitcore-node package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/start.js
18 error You can get their info via:
18 error     npm owner ls bitcore-node
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by kleetus** [comment] 2015-09-08 14:51
thanks for the stack trace. I see that your kernel is 3.19.0-15-generic, but I am curious about other aspects of your machine. If you could issue this command:

```bash
ldd <directory of bitcore-node>/build/Release/bitcoind.node
```
The output might look similar to this:

```bash
	linux-vdso.so.1 =>  (0x00007fff9279c000)
	libanl.so.1 => /lib/x86_64-linux-gnu/libanl.so.1 (0x00007f47627ed000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f476258f000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f47621b3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4761eb3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4761bb7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f47619a0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4761783000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f47613c3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4763165000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f47611be000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4760fa7000) 
```

Even better, you can always run bitcore-node through a debugger and let me know what the backtrace is:

```bash
gdb --args node <directory of bitcore-node>/bin/start
run
backtrace
```

**Comment by kleetus** [comment] 2015-09-09 16:33
I am going to experiment with this one to see if I can get this to fail like @alesfatalis

**Comment by kleetus** [comment] 2015-09-10 21:09
I am not able to reproduce this just yet.

**Comment by braydonf** [comment] 2015-09-15 15:17
I've run into a similar issue when switch between Node.js versions and was fixed by a fresh install of the node_modules.

**Comment by braydonf** [comment] 2015-09-25 18:58
Can you check again with v0.2.0-beta.8 and make sure there is a fresh install of the node modules?

**Comment by braydonf** [comment] 2015-09-25 19:02
Also you'll need to reindex by removing the `bitcoin-node.db` in the data directory of bitcoin, if you've previously run a prior beta.

**Comment by Alesfatalis** [comment] 2015-09-27 09:51
@braydonf I will try it

**Comment by braydonf** [comment] 2016-06-01 17:25
This is outdated at this point.

**Closed by braydonf** 2016-06-01 17:25 UTC
