### ISSUE TITLE
Remove need to run Bitcoin Core externally

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore-node#57] opened 2015-04-28 14:50 UTC
Current `bitcore-node` requires a running instance of Bitcoin Core (bitcoind). Remove this dependency and include it inside `bitcore-node` codebase by using https://github.com/bitpay/bitcoind.js/

**Comment by carnesen** [comment] 2015-04-29 01:29
I gather from this issue and others recently filed that the intent is to turn bitcore-node into a full node implementation instead of using the trusted-bitcoind-node architecture of its predecessor [insight-api](https://github.com/bitpay/insight-api). For my two satoshis, that would be a step in the wrong direction.

[A recent presentation by @sipa](https://youtu.be/l3O4nh79CUU?t=813) convinced me that at this stage of the game, non-Bitcoin-Core full nodes should only be used experimentally so as to minimize the risk of a fork in the blockchain, which would set back Bitcoin immeasurably. In this case the systemic risk would be particularly large due to the popularity of the bitcore modules. The *best* case scenario if a bitcore full node gets built is that nobody uses it.

The primary goal of insight-api is an open-source user-friendly web service interface to Bitcoin's data and network. That's also, I believe, the thing that Bitcoin really needs and where bitcore-node development efforts should be focused. See, for example,
* The popularity of insight-api
* Requests on Bitcoin Core for [web sockets](https://github.com/bitcoin/bitcoin/issues/3388) or some other form of [JSON push notifications](https://github.com/bitcoin/bitcoin/issues/1897)
* The fact that Bitcoin Core itself now has RESTful http endpoints, though I agree with @runeksvendsen and @gavinandresen that [it would be better to implement those features outside of Bitcoin Core](https://github.com/bitcoin/bitcoin/pull/2844#issuecomment-22262583)

What better technology for a web service interface to Bitcoin than Node.js + bitcore? (Conversely Node.js isn't a good choice for a full node implementation. See, for example, [this comment on reddit](http://www.reddit.com/r/Bitcoin/comments/2uadvd/the_real_reason_ryan_charles_was_fired_from/co6s1m2).) That's one thing that the Insight project definitely got right. That project's fundamental flaw IMO is that it duplicates a bunch of data that's already readily available from Bitcoin Core. Making bitcore-node a full node would double down on that strategy. Instead, bitcore-node should duplicate to its persistent datastore only that data which can't be accessed in a timely manner from Bitcoin Core, for example transactions that have been relayed but not confirmed, which Bitcoin Core eventually discards, and /address endpoints, for which the data is present in but not indexed by Bitcoin Core. Confirmed blocks and transactions, on the other hand, can both be accessed performantly from the existing P2P and RPC interfaces to Bitcoin Core. Therefore duplicating all that data in the insight-api/bitcore-node datastore introduces unnecessary complexity.

I understand the urge to write a full node. Satoshi felt it. @ryanxcharles [felt it](https://github.com/ryanxcharles/fullnode). I feel it. But it's not the right solution to the problem that bitcore-node/insight-api is (should be) trying to solve.

**Comment by ryanxcharles** [comment] 2015-04-29 04:36
Agreed. I'm all in favor of writing full nodes for experimental purposes, and long-term I think it may be possible to have alternative implementations that are knowably equivalent to bitcoin core. However, I don't think anybody knows how to do that quite yet, so I wouldn't rely on anything other than bitcoin core for validating blocks until that happens. But of course the only way that will happen is to write the alternative implementations - just default to bitcoin core until we are sure they are equivalent.

**Comment by gabegattis** [comment] 2015-04-29 05:10
@carnesen has important point. Bitcore-node is new and doesn't have the long history of production use that bitcoind does. Any new bitcoin software must be used with caution. We must be careful to use alternatives only when and where they are appropriate.

I disagree that alternative implementations should not be used as full nodes. I think that bitcoin _needs_ alternative implementations. Having a single implementation dominate the market is a risk. The presence of multiple alternative implementations provides some protection against bugs in any single one.

Our challenge is getting enough alternative nodes to the state where they are solid. It's a situation of, "one is better than two, but three is better than one". Having only bitcoind and one popular alternative increases the risk of forks. We need at least 2 really solid alternatives to start benefitting.

We also need alternative implementations to decentralize the decision making regarding network and protocol rules. The core dev team has a great deal of influence. We are fortunate that they have done well so far, but we still should not be completely dependent on them. We already see mining operations using their own unique policies. This doesn't extend so far as block validation rules, but a diversity of opinions about transaction priority/economics is a good thing. I would like to see more of this type of variety.

**Comment by gasteve** [comment] 2015-04-29 11:58
@carnesen our goal is to use the Bitcoin Core C++ code directly in library form that can be embedded in a nodejs process

**Comment by maraoz** [comment] 2015-04-29 14:52
@carnesen thanks for your thoughts. I agree with most of your reasoning. The issue could be more clear, but the idea is to remove bitcoind the *app* as a dependency. We'll be using C++ bindings (see https://github.com/bitpay/bitcoind.js/), and be using bitcoind as a *lib*.

**Comment by carnesen** [comment] 2015-05-07 21:54
Thanks for clarifying the plan for this project. That's some pretty advanced stuff. Let me see if I understand the bitcoind.js scenario. When the bitcore-node user does "npm install", it'll pull in bitcoind.js which'll pull in Bitcoin Core C++ source code, which gets patched and compiled. Then "npm start" instantiates a single node (as in the Node.js executable) process. The node process has its usual event loop thread as well as the threads that would have previously been in a separate bitcoind process. Similar to how bitcoind runs its database as child threads (LevelDB), bitcore-node will run bitcoind as child threads. From a birds-eye view, effectively I'll be running bitcoind with a bonus thread written in Node.js that can read blocks and transactions directly from the bitcoind disk / memory like any other normal C++ bitcoind thread. Is that the basic picture of how things will work?

**Comment by braydonf** [comment] 2015-05-21 16:04
Sounds correct. The details of how bitcoind.js would be installed still need to be figured out as the current process of compiling needs some work, as well as the initial chain synchronization.

**Comment by braydonf** [comment] 2015-06-01 01:46
So we've been able to make some progress with running Bitcoin Core code in a Node.js process and continuing @chjj's work on [bitcoind.js](https://github.com/bitpay/bitcoind.js). As an initial step, we have libbitcoinconsensus ([released as a part of Bitcoin Core 0.10.0](https://bitcoin.org/en/release/v0.10.0#consensus-library)) working with Node.js v0.10.x and 0.12.x: https://github.com/bitpay/node-libbitcoinconsensus This includes compiling on OS X, GNU/Linux *(Ubuntu)* and Windows.

**Comment by braydonf** [comment] 2015-07-31 17:16
The master branch now has Bitcoin Core running as library with Node.js bindings, and compiles on OSX and GNU/Linux (Ubuntu).

**Closed by braydonf** 2015-07-31 17:16 UTC

**Comment by maraoz** [comment] 2015-07-31 18:53
@braydonf NICE!!

**Comment by martindale** [comment] 2015-08-01 05:14
Wow, very nice work @braydonf!  Going to give this a go tomorrow – this landed at _exactly_ the right time for my project.

**Comment by braydonf** [comment] 2015-08-03 18:42
Yep, thanks to @kleetus for the great work on updating the patch and getting things to compile smoothly on both platforms. There is still a decent amount of work necessary before releasing. Next steps are to have the binaries packaged so that build tools are not necessary to run `npm install`.
